### ISSUE TITLE
Fix tabs -> two spaces

### ISSUE THREAD

**Issue by abinoam** [hanesbarbosa/alnum#3]
Hi Hanes,

I suggest you adopt a convention of "two spaces" (opposed to tabs).

Look the tabs at:
https://github.com/hanesbarbosa/alnum/blob/master/test/test_decipher.rb

**Comment by abinoam** [comment]
You could use Rubocop to spot some other "conventions".
Although some "advices" of Rubocop I am not fan of them. Like "Use single quotes string when not in need of interpolation". You can just ignore the ones you don't like.

https://github.com/bbatsov/rubocop

**Comment by hanesbarbosa** [comment]
Roger that dude!

I was using already, but some configuration on my sublime let them come up. But I'm fixing it right away.

Thanks.
