### ISSUE TITLE
Note the similarities with #to_s and #to_i

### ISSUE THREAD

**Issue by abinoam** [hanesbarbosa/alnum#6]
You can use #to_s with a base. But it uses only lowercase characters.

``` ruby
35.to_s(36)
 => "z"

36.to_s(36)
 => "10"

"z".to_i(36)
 => 35
```

**Comment by abinoam** [comment]
Just for the sake of clarity.
At the README you say you use **[0-9a-zA-Z]**
The builtin ruby conversion methods use **[0-9a-z]**

**Comment by hanesbarbosa** [comment]
Well,I ought to use both lower cases and upper ones.
