### ISSUE TITLE
Fix method invocation syntax on test

### ISSUE THREAD

**Issue by abinoam** [hanesbarbosa/alnum#7]
https://github.com/hanesbarbosa/alnum/commit/00ee0afeeb7507275abdd15e6d4272a840ef66b2#commitcomment-11441952

**Comment by abinoam** [comment]
This **::** syntax is more frequently used for namespacing like this.

``` ruby
module A
  module B
    def self.my_method
      puts "This is my method"
    end
  end
end

A::B.my_method
```

Look that 

``` ruby
A::B::my_method
```

is also a valid syntax, but it's not really used. It's confusing.

PS: 4 years ago I submited an issue to Ruby issue tracking about IRB not supporting autocompletion with this kind of invocation. Look, since then they were already inclined to deprecate this.

https://redmine.ruby-lang.org/issues/4222

**Comment by abinoam** [comment]
Hey,

Looking at Rubocop output we've got:

```
test/test_cypher.rb:8:25: C: Do not use :: for method calls.
      assert_equal Alnum::cypher(number), "#{SYMBOLS[number]}"
                        ^^
test/test_cypher.rb:14:12: C: Do not use :: for method calls.
      Alnum::cypher('a')
           ^^
```

**Comment by hanesbarbosa** [comment]
That is surely something that I missed due to the rush time, mainly due to the lack of errors when I ran the test suite.
